easy_admin:
    list:
        title: '%%entity_label%% listing'
    show:
        title: '%%entity_label%% (#%%entity_id%%)'

    entities:
        User:
            class: App\Entity\User
        Project:
            class: App\Entity\Project
        Skill:
            class: App\Entity\Skill
        Image:
            class: App\Entity\Image
            form:
                fields:
                    - { property: 'file', type: 'file' }
            list:
                fields:
                    - 'id'
                    - { property: 'web_view', type: 'image', label: 'Thumbnail' }
                    - 'filename'

    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - 'form/form.html.twig'
