<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 * @ORM\EntityListeners({"App\EntityListener\ImageListener"})
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Auto generated by entity listener
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * Auto generated by entity listener
     * @var string
     */
    private $tempFilename;

    /**
     * @var File
     * @Assert\Image()
     * @Assert\NotNull()
     */
    private $file;

    /**
     * @var string
     */
    private $webView;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(File $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getTempFilename(): ?string
    {
        return $this->tempFilename;
    }

    public function setTempFilename($filename): self
    {
        $this->tempFilename = $filename;

        return $this;
    }

    public function getWebView(): string
    {
        return $this->webView;
    }

    public function setWebView(string $webView): self
    {
        $this->webView = $webView;

        return $this;
    }

    public function __toString()
    {
        return $this->getTempFilename();
    }
}
