doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '5.7'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

    url: 'sqlite:///%kernel.project_dir%/var/data.db'
